INSERT INTO CONTRACTOR_TYPES (name) VALUES ('Firma');
INSERT INTO CONTRACTOR_TYPES (name) VALUES ('Osoba fizyczna');

INSERT INTO DOCUMENT_TYPES (name, tag) VALUES ('Przyjęcie zewnętrzne', 1);
INSERT INTO DOCUMENT_TYPES (name, tag) VALUES ('Wydanie zewnętrzne', -1);
INSERT INTO DOCUMENT_TYPES (name, tag) VALUES ('Inne (przyjęcie)', 1);
INSERT INTO DOCUMENT_TYPES (name, tag) VALUES ('Inne (wydanie)', -1);

INSERT INTO MARGIN_TYPES (TYPE_NAME) VALUES ('Procentowa');
INSERT INTO MARGIN_TYPES (TYPE_NAME) VALUES ('Kwotowa');

INSERT INTO MEASUREMENT_UNITS (UNIT_NAME) VALUES ('szt');
INSERT INTO MEASUREMENT_UNITS (UNIT_NAME) VALUES ('kg');
INSERT INTO MEASUREMENT_UNITS (UNIT_NAME) VALUES ('m');

INSERT INTO VAT_RATES (R_NAME, TAX) VALUES ('Podstawowa 23%', 23);
INSERT INTO VAT_RATES (R_NAME, TAX) VALUES ('Obniżona 8%', 8);
INSERT INTO VAT_RATES (R_NAME, TAX) VALUES ('Obniżona 5%', 5);
INSERT INTO VAT_RATES (R_NAME, TAX) VALUES ('Zwolniona 0%', 0);
INSERT INTO VAT_RATES (R_NAME, TAX) VALUES ('Nie podlega 0%', 0);
